# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: FrancoDeyvison.iClock
PackageVersion: "1.01"
InstallerType: portable
Commands:
- iClock
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/francodeyvison183-collab/iClock/releases/download/v1.01/iClock-1.01-windows.exe
  InstallerSha256: F66B6F11CB9E0C0F8B1BC869FCFE4DB23540889DEE4B3B6C1A37B74A0541F905
- Architecture: x86
  InstallerUrl: https://github.com/francodeyvison183-collab/iClock/releases/download/v1.01/iClock-1.01-windows.exe
  InstallerSha256: F66B6F11CB9E0C0F8B1BC869FCFE4DB23540889DEE4B3B6C1A37B74A0541F905
ManifestType: installer
ManifestVersion: 1.6.0
